spring:
  profiles:
    active: local
  
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/booknote}
    username: ${POSTGRES_USER:booknote}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:booknote-super-secret-key-change-this-in-production}
  access-token-ttl-minutes: ${JWT_ACCESS_TTL_MIN:15}
  refresh-token-ttl-days: ${JWT_REFRESH_TTL_DAY:14}

# AWS S3 Configuration
aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${S3_BUCKET:booknote-app}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    
# External API Keys
external:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY:}
  naver:
    client-id: ${NAVER_CLIENT_ID:}
    client-secret: ${NAVER_CLIENT_SECRET:}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      
# Logging Configuration
logging:
  level:
    com.booknote: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# Production Profile  
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  
logging:
  level:
    com.booknote: INFO
    org.springframework.security: WARN